# Generated by Django 5.0.2 on 2024-03-01 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0003_alter_cartitem_food_alter_order_address'),
        ('UserApp', '0002_alter_myuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='UserApp.useraddress'),
        ),
    ]
