# Generated by Django 5.0.2 on 2024-04-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodApp', '0006_order_total_amount_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('paid', 'Paid'), ('cod', 'Cash On Delivery'), ('pending', 'Payment is pending')], default='cod', max_length=32, verbose_name='Payment Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
