# Generated by Django 5.0.2 on 2024-03-01 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'ordering': ['-account_creation_date'], 'permissions': [('editing_access', 'Can edit food items, orders')]},
        ),
    ]
