# Generated by Django 5.0.2 on 2024-03-01 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_alter_myuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'ordering': ['-account_creation_date'], 'permissions': [('editing_access', 'Can edit food items and  orders')]},
        ),
    ]
